### ISSUE TITLE
Breaking change in pion/transport v2.2.2

### ISSUE THREAD

**Issue by hansgylling** [pion/transport#264]
### Your environment.
  - Version: v2.2.2
  - Browser: N/A
  - Other Information: N/A

### What did you do?
I updated our dependencies and got the update for pion/transport v2.2.2.

### What did you expect?
To be able to build our application without problems.

### What happened?
Compilation error because of a breaking change in pion/transport v2.2.2.

```
Error: ../../../go/pkg/mod/github.com/pion/srtp/v2@v2.0.16/option.go:37:11: cannot use &nopReplayDetector{} (value of type *nopReplayDetector) as type replaydetector.ReplayDetector in return statement:
	*nopReplayDetector does not implement replaydetector.ReplayDetector (wrong type for Check method)
		have Check(uint64) (func(), bool)
		want Check(seq uint64) (accept func() bool, ok bool)
```

The contract for Go modules is to only make breaking change in major version increases (unless the major version i 0). Since transport was at version 2.2.1 before the release of v2.2.2, you can't do breaking changes and still follow the contract for Go modules. If you want to do a breaking change, you have to release a new major version, v3.0.0.

The commit introducing the breaking change is this one: https://github.com/pion/transport/commit/d490a2cb6efc291411b66766587fb377bd15a5f7

When you fix this, you could retract release v2.2.2 in go.mod if you increase the go version in go.mod to 1.16. The retract directive was added in Go 1.16, so you would have to increase the go version for that to work.

Note that a related bug has been filed in the webrtc repo: https://github.com/pion/webrtc/issues/2544

**Comment by stv0g** [comment]
Thanks for raising this issue. It is slipped through the review. We need to revert this commit.

**Comment by Sean-Der** [comment]
Sorry again about that @hansgylling 

This weekend I will get in tooling to make sure it doesn't happen again!

**Comment by hansgylling** [comment]
Sounds great. Are you aware of the tool apidiff from the Go project? I haven't used it myself, but I believe it's made to compare APIs between versions. Could be helpful.

**Comment by Sean-Der** [comment]
I didn’t know about that! I will get that setup tonight :)

**Comment by stv0g** [comment]
I think there is already a PR in the goassets repo for apidiff

**Comment by stv0g** [comment]
See: https://github.com/pion/.goassets/pull/167

**Comment by hasheddan** [comment]
Apologies for this folks -- I mistakenly did not consider external implementors of the replay detector interface here 🤦🏻 I am in support of correcting the semver violation, though from a pragmatic perspective, I believe that the only consumers of this functionality in the `pion` org (which I acknowledge does not encompass all potential consumers) are `pion/srtp`, which has already been updated (https://github.com/pion/srtp/pull/249), and `pion/dtls`, for which this functionality was introduced. Anecdotally, `pion/dtls` has _mostly_ moved away from `pion/transport` due to a need to make significant changes that would have breaking changes.

Anyway, my apologies again for my short-sightedness here. I hope this context is helpful in determining a resolution!

**Comment by Sean-Der** [comment]
@hasheddan Not a big deal at all. I would much rather have churn then stagnation :)

* I tagged a final `v2` of pion/transport with no API breakage. 
* I tagged a `v3` with the new replaydetector API
* I am working on enabling `apidiff` support now.

I made the same mistake recently also (breaking API) so it really isn't a big deal. keep up the great work @hasheddan I love having you involved in the project!
